//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: code/unity/TankGame/Assets/proto/fight.proto
namespace code.unity.TankGame.Assets.proto.fight
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_start_fight_request")]
  public partial class c2s_start_fight_request : global::ProtoBuf.IExtensible
  {
    public c2s_start_fight_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_start_fight_reply")]
  public partial class s2c_start_fight_reply : global::ProtoBuf.IExtensible
  {
    public s2c_start_fight_reply() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_fight_request")]
  public partial class c2s_fight_request : global::ProtoBuf.IExtensible
  {
    public c2s_fight_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_fight_reply")]
  public partial class s2c_fight_reply : global::ProtoBuf.IExtensible
  {
    public s2c_fight_reply() {}
    
    private uint _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<object_info> _objects = new global::System.Collections.Generic.List<object_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"objects", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<object_info> objects
    {
      get { return _objects; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_update_unit_request")]
  public partial class c2s_update_unit_request : global::ProtoBuf.IExtensible
  {
    public c2s_update_unit_request() {}
    
    private int _pos_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private int _pos_z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private int _rot_x;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rot_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_x
    {
      get { return _rot_x; }
      set { _rot_x = value; }
    }
    private int _rot_y;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rot_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_y
    {
      get { return _rot_y; }
      set { _rot_y = value; }
    }
    private int _rot_z;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rot_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_z
    {
      get { return _rot_z; }
      set { _rot_z = value; }
    }
    private int _gun_rot;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"gun_rot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gun_rot
    {
      get { return _gun_rot; }
      set { _gun_rot = value; }
    }
    private int _gun_roll;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"gun_roll", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gun_roll
    {
      get { return _gun_roll; }
      set { _gun_roll = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_update_unit_reply")]
  public partial class s2c_update_unit_reply : global::ProtoBuf.IExtensible
  {
    public s2c_update_unit_reply() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private int _pos_z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private int _rot_x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rot_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_x
    {
      get { return _rot_x; }
      set { _rot_x = value; }
    }
    private int _rot_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rot_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_y
    {
      get { return _rot_y; }
      set { _rot_y = value; }
    }
    private int _rot_z;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rot_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_z
    {
      get { return _rot_z; }
      set { _rot_z = value; }
    }
    private int _gun_rot;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"gun_rot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gun_rot
    {
      get { return _gun_rot; }
      set { _gun_rot = value; }
    }
    private int _gun_roll;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"gun_roll", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gun_roll
    {
      get { return _gun_roll; }
      set { _gun_roll = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_shooting_request")]
  public partial class c2s_shooting_request : global::ProtoBuf.IExtensible
  {
    public c2s_shooting_request() {}
    
    private int _pos_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private int _pos_z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private int _rot_x;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rot_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_x
    {
      get { return _rot_x; }
      set { _rot_x = value; }
    }
    private int _rot_y;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rot_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_y
    {
      get { return _rot_y; }
      set { _rot_y = value; }
    }
    private int _rot_z;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rot_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_z
    {
      get { return _rot_z; }
      set { _rot_z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_shooting_reply")]
  public partial class s2c_shooting_reply : global::ProtoBuf.IExtensible
  {
    public s2c_shooting_reply() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private int _pos_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private int _pos_z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private int _rot_x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rot_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_x
    {
      get { return _rot_x; }
      set { _rot_x = value; }
    }
    private int _rot_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rot_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_y
    {
      get { return _rot_y; }
      set { _rot_y = value; }
    }
    private int _rot_z;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rot_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rot_z
    {
      get { return _rot_z; }
      set { _rot_z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_hit_request")]
  public partial class c2s_hit_request : global::ProtoBuf.IExtensible
  {
    public c2s_hit_request() {}
    
    private uint _enemy_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"enemy_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint enemy_id
    {
      get { return _enemy_id; }
      set { _enemy_id = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_hit_reply")]
  public partial class s2c_hit_reply : global::ProtoBuf.IExtensible
  {
    public s2c_hit_reply() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _enemy_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"enemy_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint enemy_id
    {
      get { return _enemy_id; }
      set { _enemy_id = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_result_request")]
  public partial class c2s_result_request : global::ProtoBuf.IExtensible
  {
    public c2s_result_request() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_result_reply")]
  public partial class s2c_result_reply : global::ProtoBuf.IExtensible
  {
    public s2c_result_reply() {}
    
    private int _camp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"object_info")]
  public partial class object_info : global::ProtoBuf.IExtensible
  {
    public object_info() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _team;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team
    {
      get { return _team; }
      set { _team = value; }
    }
    private int _swop_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"swop_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int swop_id
    {
      get { return _swop_id; }
      set { _swop_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}